### ISSUE TITLE
Poor quality 2D scan

### ISSUE THREAD

**Issue by catapulte2** [sonicwong/cordova-plugin-qrscanner-add-barcode#1]
Hi and many thanks for your efficient package. Main problem is now poor quality 2D scan. If I try to scan a 2D barcode on a bootle I will need sometime more than 30 seconds to find a way the plugin read barcode.
Did you find a way to have it mor efficient?

Regards,

Eric

**Comment by sonicwong** [comment]
@catapulte2 it is base on how the barcode being printed on product, no way to improve by software.
